### ISSUE TITLE
Support brew cask installations

### ISSUE THREAD

**Issue by zamber** [dylang/flowdock-refined#2]
Looks like `brew cask install flowdock` does not go well with the installation script :).

**Comment by dylang** [comment]
Hi - can you explain what you mean by "does not go well." 

I'm not sure what that brew command does. If it's installing Flowdock in a different directly let me know where the files should be copied to. If it's installing an older version of Flowdock it may not work.

**Comment by zamber** [comment]
There are no changes visible.

[Cask](https://github.com/phinze/homebrew-cask) installs flowdock to ~~`/opt/homebrew-cask/Caskroom/flowdock/1.1.0/Flowdock.app/`~~  `/opt/homebrew-cask/Caskroom/flowdock/latest` (had an [older version](https://github.com/phinze/homebrew-cask/commit/f3d500dac99fec5ca692698af7c9d0ed78810d94)). 

This will probably not change in the foreseeable future :).

**Comment by zamber** [comment]
Looks like the instalation is successful.

![screen shot 2014-04-15 at 18 16 05](https://cloud.githubusercontent.com/assets/557066/2709723/5991028c-c4b9-11e3-8a09-899b7bf19f04.png)

the style-src directive effectively prevents the css from loading.

You could bundle some visual info as it looks like automatic updates will not work. A background image renamed with each following release? It could be injected with :before somewhere.

**Comment by dylang** [comment]
I'm not sure why you are getting that error. Works fine for everyone else that has tried it, though I don't know that anybody else uses `cask`.

This is Flowdock 1.1.8 (21)?

**Comment by zamber** [comment]
![screen shot 2014-04-15 at 18 27 53](https://cloud.githubusercontent.com/assets/557066/2709867/e9ec34a4-c4ba-11e3-8525-9220e5b9fbf3.png)

Yep.

Cask is probably unrelated here as it loads the user stylesheet (or at least tries).

You could try getting Flowdock from https://flowdock-resources.s3.amazonaws.com/mac/Flowdock.zip to see if it wasn't changed in the MacGap wrapper.

**Comment by dylang** [comment]
So i don't understand why your install has a Content Security Policy and mine doesn't. Do you know where it's set?

Not sure if it matters, I'm using the last OS X with the latest Safari.

**Comment by zamber** [comment]
This is defined in the HTTP header of the host site ((src)[http://www.html5rocks.com/en/tutorials/security/content-security-policy/]) so it should touch you too. Sure you've got the latest?

**Comment by dylang** [comment]
Ah shitters, I just restarted Flowdock for the first time in a while and now it's blocking me as well.

Guess I'll publish a new version without automatic updates. Sad.

**Comment by zamber** [comment]
Damn that Cross Origin Policy spawn. Always breaking things ;).

**Comment by dylang** [comment]
:) Fixing coming soon. Thanks for the help debugging.

Are any changes needed for Cask?

**Comment by dylang** [comment]
reinstall and try again

**Comment by dylang** [comment]
`npm install -g flowdock-refined` i mean, not flowdock.

**Comment by zamber** [comment]
Works like a charm, thanks :)!
